### ISSUE TITLE
Better name - suggestions welcome

### ISSUE THREAD

**Issue by anlutro** [anlutro/botologist#12]
"ircbot" is too generic and boring.

Suggestions: eggwithhair, riceburner, Nigbot, Pillow, Highest Order Flower, bob-xd, pep420, utøyanlutro, notwork, nowork, botnowork, mrpoopybutthole, ebaegkgbot, carbot, Botologist, sup

**Comment by EricBisceglia** [comment]
In honor of eggbot being a classic irc bot name and your face looking like an egg with hair, I suggest eggwithhair

**Comment by x89** [comment]
But then you are too so it works out well, no?

**Comment by EricBisceglia** [comment]
Another suggestion would be riceburner

**Comment by moopie** [comment]
I suggest the name 'Nigbot' in honor of the original redditeu bot

**Comment by anlutro** [comment]
Pillow

**Comment by EricBisceglia** [comment]
Will continue shitty suggestions with garner's « bé🐭🍗🐰🐽 », easy to type and say out loud

**Comment by anlutro** [comment]
Highest Order Flower

**Comment by anlutro** [comment]
bob-xd

**Comment by EricBisceglia** [comment]
pep420 since it's a python bot

**Comment by EricBisceglia** [comment]
utoyanlutro

**Comment by moopie** [comment]
notwork

**Comment by moopie** [comment]
wankbot

**Comment by moopie** [comment]
mrpoopybutthole

**Comment by moopie** [comment]
ebaegkgbot

**Comment by anlutro** [comment]
@moopie you're so childish.

**Comment by Garner071** [comment]
lol^. I would suggest one of the typos for your name.

**Comment by moopie** [comment]
@Garner071 please provide typos tho

**Comment by x89** [comment]
Guys

**Comment by x89** [comment]
Internet has gone down again, mad.

**Comment by anlutro** [comment]
@x89 this isn't IRC or whatsapp, dude

**Comment by moopie** [comment]
nice spam you guys

**Comment by EricBisceglia** [comment]
I am currently sitting in my chair fyi

**Comment by moopie** [comment]
great name for bot
carbot

**Comment by x89** [comment]
Carbot ®™©

**Comment by anlutro** [comment]
Botologist (thanks Eric)

**Comment by x89** [comment]
Stfu I'm watching a film.

**Comment by EricBisceglia** [comment]
What movie you watchin D

**Comment by x89** [comment]
Gone Girl! Pretty good!

**Comment by EricBisceglia** [comment]
Hm I'm yet to watch it, have fun and leave a criticker

**Comment by x89** [comment]
Will do, say hi to raziel for me.

**Comment by EricBisceglia** [comment]
22:26:07 <Bad> Raziel: Naypam says hi

**Comment by moopie** [comment]
another great name:
"sup"

**Comment by FredG71** [comment]
Currently having a drink, it's pretty cold btw.

**Comment by anlutro** [comment]
> Currently having a drink

Don't let David near it

**Comment by FredG71** [comment]
He can't get near it, he's in jail.

**Comment by x89** [comment]
Ohh I have one in the fridge, ty for the reminder!

**Comment by anlutro** [comment]
Your best suggestions were unfit for the public. Sorry

**Comment by moopie** [comment]
please reopen the issue because the current name is bad and you should feel bad

**Comment by anlutro** [comment]
You're free to keep discussing even if the issue is closed.

**Comment by moopie** [comment]
But this implies that the issue was resolved, which is not true

**Comment by anlutro** [comment]
As the owner of the project that's up for me to decide
