### ISSUE TITLE
reduce github spam

### ISSUE THREAD

**Issue by moopie** [anlutro/botologist#22]
every time you do a new issue ircbot notifies the channel about it

with a growing popularity of ircbot this might cause a problem

pls fix

bot no work

**Comment by x89** [comment]
We actually also need comments to appear in IRC.

**Comment by anlutro** [comment]
It's not that frequent. It's like <10 a day most of the time. I think you powerusers could just set up a regex filter if you find it annoying.

**Comment by moopie** [comment]
Look at this shit

![screenshot from 2015-08-29 12-04-13](https://cloud.githubusercontent.com/assets/271154/9561250/18f6e440-4e46-11e5-97bb-4098b582383e.png)

**Comment by anlutro** [comment]
That's weechat spam, not the bot ;)

**Comment by moopie** [comment]
harsh
