### ISSUE TITLE
Find a better name for botologist

### ISSUE THREAD

**Issue by moopie** [anlutro/botologist#24]
'botologist'?

who came up with that?

**Comment by FredG71** [comment]
Raziel did

**Comment by moopie** [comment]
fix

**Comment by FredG71** [comment]
imo change bot name to moopie

**Comment by moopie** [comment]
poopologist

**Comment by EricBisceglia** [comment]
Agree that it's a completely garbage name. There were so many good suggestions, this one is awful.

**Comment by FredG71** [comment]
He could have called it tunnel

**Comment by anlutro** [comment]
Keep it in the original issue please
