### ISSUE TITLE
Currency aliases

### ISSUE THREAD

**Issue by anlutro** [anlutro/botologist#27]
We should have aliases for currencies - a dict on the `Currency` class with lookups like `'euro': 'eur', 'euros': 'eur'` etc.

@moopie has volunteered to do this on IRC.

**Comment by moopie** [comment]
who is this @moopie you speak of

**Comment by FredG71** [comment]
Yes @moopie volunteered, I'm a witness. :-)

**Comment by anlutro** [comment]
@moopie I don't know who @moopie is.
