### ISSUE TITLE
Command aliases

### ISSUE THREAD

**Issue by anlutro** [anlutro/botologist#31]
Should be possible to easily define command aliases. Some suggestions for syntax:

```python
@command('cmd', alias='c', threaded=True)
@command('cmd', alias=['c', 'cm'], threaded=True)
@command('cmd', 'c', threaded=True)
```

**Comment by FredG71** [comment]
@x89

**Comment by x89** [comment]
Shag me very roughly.

**Comment by FredG71** [comment]
Why did I get an email notification @x89?

**Comment by anlutro** [comment]
Why did I get an email notification @x89 @FredG71 ?
