### ISSUE TITLE
Fix !time

### ISSUE THREAD

**Issue by moopie** [anlutro/botologist#59]
Time is broken. Please fix it.

```
<FredG> !time
<__bot__> the time is 26:07 PM
```

**Comment by anlutro** [comment]
What exactly is the problem?

**Comment by moopie** [comment]
Time is broken.

**Comment by anlutro** [comment]
I'm not in control of time.

**Comment by moopie** [comment]
As you can clearly see in the screenshot I provided, __bot__ can't time.

**Comment by anlutro** [comment]
Looks fine to me. Also, it's not a screenshot

**Comment by moopie** [comment]
Clearly you can't look properly because the time is not correct.

**Comment by moopie** [comment]
Also omg it's so nice github is so responsive it's like a chat

**Comment by anlutro** [comment]
```
08:59 <Raziel> !time
08:59 <__bot__> the time is 08:59 AM
```

Can't reproduce

**Comment by moopie** [comment]
Another screenshot:

```
09:58	<+Raziel>	!time
09:58	<__bot__>	the time is -8:11 AM
09:58	<+Raziel>	!time
09:58	<__bot__>	the time is -21:68 PM
09:58	<+Raziel>	!time
09:58	<__bot__>	the time is -6:56 AM
09:58	<+Raziel>	!time
09:58	<__bot__>	the time is 16:41 AM
09:58	<+Raziel>	!time
09:58	<__bot__>	the time is -4:27 PM
09:58	<+Raziel>	!time
09:58	<__bot__>	the time is -19:61 AM
09:59	<+Raziel>	!time
09:59	<__bot__>	the time is 19:20 AM
```

**Comment by moopie** [comment]
Please reopen the issue.

**Comment by moopie** [comment]
![image](https://cloud.githubusercontent.com/assets/271154/11061067/efff0176-87ac-11e5-9f39-1c170fcda384.png)

**Comment by Happy0** [comment]
Please don't fix this bug. It will break my workflow.

**Comment by anlutro** [comment]
It's not a bug
