### ISSUE TITLE
twitch api changes

### ISSUE THREAD

**Issue by moopie** [anlutro/botologist#75]
now twitch requires authentication

add auth

**Comment by anlutro** [comment]
To elaborate: We need an auth token as documented here: https://github.com/justintv/Twitch-API/blob/master/authentication.md

Need to figure out which scopes we need.

**Comment by anlutro** [comment]
Judging by how livestreamer does it, it looks like we don't need any scopes. A key generated without a scope will work for fetching stream status, title etc..

**Comment by moopie** [comment]
good job sir @anlutro
