### ISSUE TITLE
Add command for getting tv show info

### ISSUE THREAD

**Issue by anlutro** [anlutro/botologist#84]
Most interesting: When is next episode?

**Comment by anlutro** [comment]
http://api.tvmaze.com/singlesearch/shows?q=game+of+thrones

Contains a link to "nextepisode":

http://api.tvmaze.com/episodes/937256

Which has a timestamp with timezone for when the next episode is.

**Comment by anlutro** [comment]
Nevermind, just use http://api.tvmaze.com/singlesearch/shows?q=game+of+thrones&embed=nextepisode which has all the info in 1 query

**Comment by FredG71** [comment]
Thinking
